/*
 * Copyright (c) 2024 triaxis s.r.o.
 * Licensed under the MIT license. See LICENSE.txt file in the repository root
 * for full license information.
 *
 * lvgl/lvgl-lib.c
 * 
 * Compiles the entire LVGL library in a single file to allow inter-module
 * optimizations
 * 
 * The file list is generated simply using
 * 
 * ```
 * find src -iname '*.c' | sort | awk '$0="#include <"$0">"'
 * ```
 * 
 * additional #undefs a #defines were added by hand to resolve conflicting symbols
 * 
 * sw_blend files are compiled individually because they have too many overlapping names
 */

#include <lvgl.h>

#pragma GCC optimize("O3", "Os")

#include <src/core/lv_group.c>
#include <src/core/lv_obj.c>
#include <src/core/lv_obj_class.c>
#include <src/core/lv_obj_draw.c>
#include <src/core/lv_obj_event.c>
#include <src/core/lv_obj_id_builtin.c>
#include <src/core/lv_obj_pos.c>
#include <src/core/lv_obj_property.c>
#include <src/core/lv_obj_scroll.c>
#include <src/core/lv_obj_style.c>
#include <src/core/lv_obj_style_gen.c>
#include <src/core/lv_obj_tree.c>
#include <src/core/lv_refr.c>
#include <src/display/lv_display.c>
#include <src/draw/lv_draw.c>
#include <src/draw/lv_draw_arc.c>
#include <src/draw/lv_draw_buf.c>
#include <src/draw/lv_draw_image.c>
#undef font_draw_buf_handlers
#include <src/draw/lv_draw_label.c>
#include <src/draw/lv_draw_line.c>
#include <src/draw/lv_draw_mask.c>
#include <src/draw/lv_draw_rect.c>
#include <src/draw/lv_draw_triangle.c>
#include <src/draw/lv_draw_vector.c>
#undef image_cache_draw_buf_handlers
#include <src/draw/lv_image_decoder.c>
#include <src/draw/nxp/pxp/lv_draw_buf_pxp.c>
#include <src/draw/nxp/pxp/lv_draw_pxp.c>
#include <src/draw/nxp/pxp/lv_draw_pxp_fill.c>
#include <src/draw/nxp/pxp/lv_draw_pxp_img.c>
#include <src/draw/nxp/pxp/lv_draw_pxp_layer.c>
#include <src/draw/nxp/pxp/lv_pxp_cfg.c>
#include <src/draw/nxp/pxp/lv_pxp_osa.c>
#include <src/draw/nxp/pxp/lv_pxp_utils.c>
#include <src/draw/nxp/vglite/lv_draw_buf_vglite.c>
#include <src/draw/nxp/vglite/lv_draw_vglite.c>
#include <src/draw/nxp/vglite/lv_draw_vglite_arc.c>
#include <src/draw/nxp/vglite/lv_draw_vglite_border.c>
#include <src/draw/nxp/vglite/lv_draw_vglite_fill.c>
#include <src/draw/nxp/vglite/lv_draw_vglite_img.c>
#include <src/draw/nxp/vglite/lv_draw_vglite_label.c>
#include <src/draw/nxp/vglite/lv_draw_vglite_layer.c>
#include <src/draw/nxp/vglite/lv_draw_vglite_line.c>
#include <src/draw/nxp/vglite/lv_draw_vglite_triangle.c>
#include <src/draw/nxp/vglite/lv_vglite_buf.c>
#include <src/draw/nxp/vglite/lv_vglite_matrix.c>
#include <src/draw/nxp/vglite/lv_vglite_path.c>
#include <src/draw/nxp/vglite/lv_vglite_utils.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d_arc.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d_border.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d_fill.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d_image.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d_label.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d_line.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d_mask_rectangle.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d_triangle.c>
#include <src/draw/renesas/dave2d/lv_draw_dave2d_utils.c>
#include <src/draw/sdl/lv_draw_sdl.c>
#include <src/draw/sw/lv_draw_sw.c>
#include <src/draw/sw/lv_draw_sw_arc.c>
#include <src/draw/sw/lv_draw_sw_border.c>
#include <src/draw/sw/lv_draw_sw_box_shadow.c>
#include <src/draw/sw/lv_draw_sw_fill.c>
#include <src/draw/sw/lv_draw_sw_gradient.c>
#include <src/draw/sw/lv_draw_sw_img.c>
#include <src/draw/sw/lv_draw_sw_letter.c>
#include <src/draw/sw/lv_draw_sw_line.c>
#include <src/draw/sw/lv_draw_sw_mask.c>
#include <src/draw/sw/lv_draw_sw_mask_rect.c>
#include <src/draw/sw/lv_draw_sw_transform.c>
#include <src/draw/sw/lv_draw_sw_triangle.c>
#include <src/draw/sw/lv_draw_sw_vector.c>
#include <src/draw/vg_lite/lv_draw_buf_vg_lite.c>
#include <src/draw/vg_lite/lv_draw_vg_lite.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_arc.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_border.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_box_shadow.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_fill.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_img.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_label.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_layer.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_line.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_mask_rect.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_triangle.c>
#include <src/draw/vg_lite/lv_draw_vg_lite_vector.c>
#include <src/draw/vg_lite/lv_vg_lite_decoder.c>
#include <src/draw/vg_lite/lv_vg_lite_grad.c>
#include <src/draw/vg_lite/lv_vg_lite_math.c>
#include <src/draw/vg_lite/lv_vg_lite_path.c>
#include <src/draw/vg_lite/lv_vg_lite_pending.c>
#include <src/draw/vg_lite/lv_vg_lite_stroke.c>
#include <src/draw/vg_lite/lv_vg_lite_utils.c>
#include <src/drivers/display/drm/lv_linux_drm.c>
#include <src/drivers/display/fb/lv_linux_fbdev.c>
#include <src/drivers/display/ili9341/lv_ili9341.c>
#include <src/drivers/display/lcd/lv_lcd_generic_mipi.c>
#include <src/drivers/display/renesas_glcdc/lv_renesas_glcdc.c>
#include <src/drivers/display/st7735/lv_st7735.c>
#include <src/drivers/display/st7789/lv_st7789.c>
#include <src/drivers/display/st7796/lv_st7796.c>
#include <src/drivers/evdev/lv_evdev.c>
#include <src/drivers/glfw/lv_glfw_window.c>
#include <src/drivers/glfw/lv_opengles_debug.c>
#include <src/drivers/glfw/lv_opengles_driver.c>
#include <src/drivers/glfw/lv_opengles_texture.c>
#include <src/drivers/libinput/lv_libinput.c>
#include <src/drivers/libinput/lv_xkb.c>
#include <src/drivers/nuttx/lv_nuttx_cache.c>
#include <src/drivers/nuttx/lv_nuttx_entry.c>
#include <src/drivers/nuttx/lv_nuttx_fbdev.c>
#include <src/drivers/nuttx/lv_nuttx_image_cache.c>
#include <src/drivers/nuttx/lv_nuttx_lcd.c>
#include <src/drivers/nuttx/lv_nuttx_libuv.c>
#include <src/drivers/nuttx/lv_nuttx_profiler.c>
#include <src/drivers/nuttx/lv_nuttx_touchscreen.c>
#include <src/drivers/qnx/lv_qnx.c>
#include <src/drivers/sdl/lv_sdl_keyboard.c>
#include <src/drivers/sdl/lv_sdl_mouse.c>
#include <src/drivers/sdl/lv_sdl_mousewheel.c>
#include <src/drivers/sdl/lv_sdl_window.c>
#include <src/drivers/wayland/lv_wayland.c>
#include <src/drivers/wayland/lv_wayland_smm.c>
#include <src/drivers/windows/lv_windows_context.c>
#include <src/drivers/windows/lv_windows_display.c>
#include <src/drivers/windows/lv_windows_input.c>
#include <src/drivers/x11/lv_x11_display.c>
#include <src/drivers/x11/lv_x11_input.c>
#include <src/font/lv_binfont_loader.c>
#include <src/font/lv_font.c>
#include <src/font/lv_font_dejavu_16_persian_hebrew.c>
#include <src/font/lv_font_fmt_txt.c>
#include <src/font/lv_font_montserrat_10.c>
#include <src/font/lv_font_montserrat_12.c>
#include <src/font/lv_font_montserrat_14.c>
#include <src/font/lv_font_montserrat_16.c>
#include <src/font/lv_font_montserrat_18.c>
#include <src/font/lv_font_montserrat_20.c>
#include <src/font/lv_font_montserrat_22.c>
#include <src/font/lv_font_montserrat_24.c>
#include <src/font/lv_font_montserrat_26.c>
#include <src/font/lv_font_montserrat_28.c>
#include <src/font/lv_font_montserrat_28_compressed.c>
#include <src/font/lv_font_montserrat_30.c>
#include <src/font/lv_font_montserrat_32.c>
#include <src/font/lv_font_montserrat_34.c>
#include <src/font/lv_font_montserrat_36.c>
#include <src/font/lv_font_montserrat_38.c>
#include <src/font/lv_font_montserrat_40.c>
#include <src/font/lv_font_montserrat_42.c>
#include <src/font/lv_font_montserrat_44.c>
#include <src/font/lv_font_montserrat_46.c>
#include <src/font/lv_font_montserrat_48.c>
#include <src/font/lv_font_montserrat_8.c>
#include <src/font/lv_font_simsun_14_cjk.c>
#include <src/font/lv_font_simsun_16_cjk.c>
#include <src/font/lv_font_unscii_16.c>
#include <src/font/lv_font_unscii_8.c>
#include <src/indev/lv_indev.c>
#include <src/indev/lv_indev_scroll.c>
#include <src/layouts/flex/lv_flex.c>
#include <src/layouts/grid/lv_grid.c>
#include <src/layouts/lv_layout.c>
#include <src/libs/barcode/code128.c>
#include <src/libs/barcode/lv_barcode.c>
#include <src/libs/bin_decoder/lv_bin_decoder.c>
#include <src/libs/bmp/lv_bmp.c>
#include <src/libs/ffmpeg/lv_ffmpeg.c>
#include <src/libs/freetype/lv_freetype.c>
#include <src/libs/freetype/lv_freetype_glyph.c>
#include <src/libs/freetype/lv_freetype_image.c>
#include <src/libs/freetype/lv_freetype_outline.c>
#include <src/libs/freetype/lv_ftsystem.c>
#include <src/libs/fsdrv/lv_fs_cbfs.c>
#include <src/libs/fsdrv/lv_fs_fatfs.c>
#include <src/libs/fsdrv/lv_fs_littlefs.c>
#include <src/libs/fsdrv/lv_fs_memfs.c>
#include <src/libs/fsdrv/lv_fs_posix.c>
#include <src/libs/fsdrv/lv_fs_stdio.c>
#include <src/libs/fsdrv/lv_fs_win32.c>
#include <src/libs/gif/gifdec.c>
#include <src/libs/gif/lv_gif.c>
#include <src/libs/libjpeg_turbo/lv_libjpeg_turbo.c>
#include <src/libs/libpng/lv_libpng.c>
#include <src/libs/lodepng/lodepng.c>
#include <src/libs/lodepng/lv_lodepng.c>
#include <src/libs/lz4/lz4.c>
#include <src/libs/qrcode/lv_qrcode.c>
#include <src/libs/qrcode/qrcodegen.c>
#include <src/libs/rle/lv_rle.c>
#include <src/libs/rlottie/lv_rlottie.c>
#include <src/libs/tiny_ttf/lv_tiny_ttf.c>
#include <src/libs/tjpgd/lv_tjpgd.c>
#include <src/libs/tjpgd/tjpgd.c>
#include <src/lv_init.c>
#include <src/misc/cache/lv_cache.c>
#include <src/misc/cache/lv_cache_entry.c>
#include <src/misc/cache/lv_cache_lru_rb.c>
#include <src/misc/cache/lv_image_cache.c>
#undef CACHE_NAME
#undef IMAGE_CACHE_DUMP_FORMAT
#define image_cache_common_compare image_cache_common_compare2
#define iter_inspect_cb iter_inspect_cb2
#include <src/misc/cache/lv_image_header_cache.c>
#include <src/misc/lv_anim.c>
#undef state
#include <src/misc/lv_anim_timeline.c>
#include <src/misc/lv_area.c>
#include <src/misc/lv_array.c>
#include <src/misc/lv_async.c>
#include <src/misc/lv_bidi.c>
#include <src/misc/lv_color.c>
#include <src/misc/lv_color_op.c>
#include <src/misc/lv_event.c>
#include <src/misc/lv_fs.c>
#include <src/misc/lv_ll.c>
#include <src/misc/lv_log.c>
#include <src/misc/lv_lru.c>
#include <src/misc/lv_math.c>
#include <src/misc/lv_matrix.c>
#include <src/misc/lv_palette.c>
#include <src/misc/lv_profiler_builtin.c>
#include <src/misc/lv_rb.c>
#include <src/misc/lv_style.c>
#include <src/misc/lv_style_gen.c>
#include <src/misc/lv_templ.c>
#include <src/misc/lv_text.c>
#include <src/misc/lv_text_ap.c>
#include <src/misc/lv_timer.c>
#undef state
#include <src/misc/lv_utils.c>
#include <src/osal/lv_cmsis_rtos2.c>
#include <src/osal/lv_freertos.c>
#include <src/osal/lv_mqx.c>
#include <src/osal/lv_os.c>
#include <src/osal/lv_os_none.c>
#include <src/osal/lv_pthread.c>
#include <src/osal/lv_rtthread.c>
#include <src/osal/lv_windows.c>
#include <src/others/file_explorer/lv_file_explorer.c>
#include <src/others/fragment/lv_fragment.c>
#include <src/others/fragment/lv_fragment_manager.c>
#include <src/others/gridnav/lv_gridnav.c>
#include <src/others/ime/lv_ime_pinyin.c>
#include <src/others/imgfont/lv_imgfont.c>
#include <src/others/monkey/lv_monkey.c>
#include <src/others/observer/lv_observer.c>
#include <src/others/snapshot/lv_snapshot.c>
#include <src/others/sysmon/lv_sysmon.c>
#include <src/others/vg_lite_tvg/vg_lite_matrix.c>
#include <src/stdlib/builtin/lv_mem_core_builtin.c>
#undef state
#include <src/stdlib/builtin/lv_sprintf_builtin.c>
#include <src/stdlib/builtin/lv_string_builtin.c>
#include <src/stdlib/builtin/lv_tlsf.c>
#include <src/stdlib/clib/lv_mem_core_clib.c>
#include <src/stdlib/clib/lv_sprintf_clib.c>
#include <src/stdlib/clib/lv_string_clib.c>
#include <src/stdlib/lv_mem.c>
#include <src/stdlib/micropython/lv_mem_core_micropython.c>
#include <src/stdlib/rtthread/lv_mem_core_rtthread.c>
#include <src/stdlib/rtthread/lv_sprintf_rtthread.c>
#include <src/stdlib/rtthread/lv_string_rtthread.c>
#include <src/themes/lv_theme.c>
#include <src/tick/lv_tick.c>
#undef state
#undef MY_CLASS
#include <src/widgets/animimage/lv_animimage.c>
#undef MY_CLASS
#include <src/widgets/arc/lv_arc.c>
#undef MY_CLASS
#include <src/widgets/bar/lv_bar.c>
#undef MY_CLASS
#undef state
#include <src/widgets/button/lv_button.c>
#undef MY_CLASS
#include <src/widgets/buttonmatrix/lv_buttonmatrix.c>
#undef MY_CLASS
#include <src/widgets/calendar/lv_calendar.c>
#undef MY_CLASS
#include <src/widgets/calendar/lv_calendar_chinese.c>
#undef MY_CLASS
#include <src/widgets/calendar/lv_calendar_header_arrow.c>
#undef MY_CLASS
#define my_constructor my_constructor2
#define month_event_cb month_event_cb2
#define value_changed_event_cb value_changed_event_cb2
#include <src/widgets/calendar/lv_calendar_header_dropdown.c>
#undef MY_CLASS
#include <src/widgets/canvas/lv_canvas.c>
#undef MY_CLASS
#include <src/widgets/chart/lv_chart.c>
#undef MY_CLASS
#include <src/widgets/checkbox/lv_checkbox.c>
#undef MY_CLASS
#define draw_main draw_main2
#include <src/widgets/dropdown/lv_dropdown.c>
#undef MY_CLASS
#include <src/widgets/image/lv_image.c>
#undef MY_CLASS
#undef draw_main
#define draw_main draw_main3
#include <src/widgets/imagebutton/lv_imagebutton.c>
#undef MY_CLASS
#include <src/widgets/keyboard/lv_keyboard.c>
#undef MY_CLASS
#undef draw_main
#define draw_main draw_main4
#include <src/widgets/label/lv_label.c>
#undef MY_CLASS
#include <src/widgets/led/lv_led.c>
#undef MY_CLASS
#include <src/widgets/line/lv_line.c>
#undef MY_CLASS
#include <src/widgets/list/lv_list.c>
#undef MY_CLASS
#include <src/widgets/lottie/lv_lottie.c>
#undef MY_CLASS
#include <src/widgets/menu/lv_menu.c>
#undef MY_CLASS
#include <src/widgets/msgbox/lv_msgbox.c>
#include <src/widgets/objx_templ/lv_objx_templ.c>
#include <src/widgets/property/lv_dropdown_properties.c>
#include <src/widgets/property/lv_image_properties.c>
#include <src/widgets/property/lv_keyboard_properties.c>
#include <src/widgets/property/lv_label_properties.c>
#include <src/widgets/property/lv_obj_properties.c>
#include <src/widgets/property/lv_roller_properties.c>
#include <src/widgets/property/lv_style_properties.c>
#include <src/widgets/property/lv_textarea_properties.c>
#undef MY_CLASS
#undef draw_main
#define draw_main draw_main5
#define get_label get_label2
#define set_y_anim set_y_anim2
#include <src/widgets/roller/lv_roller.c>
#undef MY_CLASS
#include <src/widgets/scale/lv_scale.c>
#undef MY_CLASS
#include <src/widgets/slider/lv_slider.c>
#undef MY_CLASS
#undef draw_main
#define draw_main draw_main6
#include <src/widgets/span/lv_span.c>
#undef MY_CLASS
#include <src/widgets/spinbox/lv_spinbox.c>
#undef MY_CLASS
#include <src/widgets/spinner/lv_spinner.c>
#undef MY_CLASS
#undef draw_main
#define draw_main draw_main7
#include <src/widgets/switch/lv_switch.c>
#undef MY_CLASS
#undef draw_main
#define draw_main draw_main8
#include <src/widgets/table/lv_table.c>
#undef MY_CLASS
#include <src/widgets/tabview/lv_tabview.c>
#undef MY_CLASS
#include <src/widgets/textarea/lv_textarea.c>
#undef MY_CLASS
#include <src/widgets/tileview/lv_tileview.c>
#undef MY_CLASS
#include <src/widgets/win/lv_win.c>
